#!/usr/bin/env bash
# Pane entrypoint: assemble the layered lazygit configuration, then exec lazygit.
#
# Config layering (verified against lazygit's docs/Config.md: LG_CONFIG_FILE
# accepts a comma-separated list of config files, later files merged over
# earlier ones):
#   0. the user's OWN lazygit config (default dir reported by the binary via
#      --print-config-dir) — so an existing lazygit user keeps their theme and
#      settings inside the pane; INHERIT_USER_CONFIG=0 in panel.conf disables
#   1. $PLUGIN_ROOT/lazygit-config.yml           — the plugin's bundled config
#      (gui defaults only; all plugin commands live in the generated layer)
#   2. $HERDR_PLUGIN_CONFIG_DIR/generated.yml    — machine-generated by
#      scripts/gen-config-layer.sh from keys.conf (plugin customCommands:
#      AI commit / expand / settings); regenerated before every launch
#   3. $HERDR_PLUGIN_CONFIG_DIR/layout-*.yml     — per-pane layout layer
#      created here (sidebar by default, expanded after KEY_ZOOM)
#   4. $HERDR_PLUGIN_CONFIG_DIR/lazygit-user.yml — the user's override layer,
#      created empty (comments only) on first run; survives plugin updates
#      and always wins.
#
# NOTE: a missing file in LG_CONFIG_FILE is a hard startup error, so the
# generated layer is only appended when it actually exists.
#
# HERDR_LAZYGIT_ROOT is exported so the bundled config's customCommands can
# locate the plugin's scripts (e.g. scripts/ai-commit-msg.sh) by absolute path.
#
# bash 3.2 compatible (macOS default).
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
PLUGIN_ROOT="$(cd "$script_dir/.." && pwd)"
export HERDR_LAZYGIT_ROOT="$PLUGIN_ROOT"
# shellcheck disable=SC1091
. "$script_dir/runtime-env.sh"
herdr_lazygit_require_runtime lazygit
# shellcheck disable=SC1091
. "$script_dir/layout-layer.sh"

# Resolved by runtime-env.sh: HERDR_PLUGIN_CONFIG_DIR when herdr injects it,
# else a sensible per-user dir so the script also works when run outside herdr.
config_dir="$HERDR_LAZYGIT_CONFIG_DIR"
mkdir -p "$config_dir"
panel_conf="$config_dir/panel.conf"

# Each lazygit pane owns its own layout layer. Before creating the new one,
# remove orphaned layout-*.yml files whose pid component no longer exists.
herdr_lazygit_cleanup_stale_layout_layers "$config_dir"
layout_epoch="$(date +%s 2>/dev/null || printf '0')"
layout_file="$config_dir/layout-$$-$layout_epoch.yml"
herdr_lazygit_write_layout_layer "$layout_file" "sidebar"
export HERDR_LAZYGIT_LAYOUT_FILE="$layout_file"

user_config="$config_dir/lazygit-user.yml"
if [ ! -f "$user_config" ]; then
  cat > "$user_config" <<'EOF'
# lazygit-user.yml — your personal override layer for the herdr-lazygit plugin.
#
# Settings here are merged OVER the plugin's bundled lazygit-config.yml
# (lazygit merges the comma-separated LG_CONFIG_FILE list left to right).
# Add any lazygit config keys you want to customize, e.g.:
#
#   gui:
#     nerdFontsVersion: "3"
#
# Full reference: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
EOF
fi

# Generate the intermediate layer (idempotent, with only stat-level overhead
# when inputs are unchanged). Failure does not block startup: without
# generated.yml, degrade to the bundled + per-pane layout + user layers and
# temporarily lose only plugin keybindings.
bash "$script_dir/gen-config-layer.sh" || true

# Layer 0 (default on): the user's own lazygit config, so an existing lazygit
# user keeps their theme and settings inside the pane. The plugin's layers
# merge OVER it, so keys the plugin owns still win. INHERIT_USER_CONFIG=0 in
# panel.conf disables it. The config dir is reported by the lazygit binary
# itself (--print-config-dir), which answers the macOS/Linux/XDG path question
# version-correctly. Read the flag in a subshell so a broken panel.conf cannot
# kill the pane (mirrors gen-config-layer.sh's pattern).
inherit_user_config=""
if [ -f "$panel_conf" ]; then
  inherit_user_config="$(
    ( . "$panel_conf" >/dev/null 2>&1 || exit 0
      printf '%s' "${INHERIT_USER_CONFIG:-}" ) 2>/dev/null
  )"
fi
layers=""
if [ "$inherit_user_config" != "0" ]; then
  own_dir="$(env -u LG_CONFIG_FILE "$HERDR_LAZYGIT_BIN" --print-config-dir 2>/dev/null || true)"
  if [ -n "$own_dir" ] && [ -f "$own_dir/config.yml" ]; then
    layers="$own_dir/config.yml,"
  fi
fi

generated="$config_dir/generated.yml"
layers="$layers$PLUGIN_ROOT/lazygit-config.yml"
if [ -f "$generated" ]; then
  layers="$layers,$generated"
fi
layers="$layers,$layout_file,$user_config"

export LG_CONFIG_FILE="$layers"

# Run lazygit as a child (not exec) so a startup failure — for example an
# inherited personal config with keys this pinned lazygit does not know —
# leaves a readable error in the pane instead of closing it instantly.
status=0
"$HERDR_LAZYGIT_BIN" || status=$?
if [ "$status" -ne 0 ]; then
  {
    printf '\nherdr-lazygit: lazygit exited with status %d.\n' "$status"
    printf 'Config layers (merged left to right):\n'
    printf '%s\n' "$layers" | tr ',' '\n' | sed 's/^/  /'
    printf 'If the error above points at an inherited personal config, fix that key or set\n'
    printf 'INHERIT_USER_CONFIG=0 in %s\n' "$panel_conf"
  } >&2
  if [ -t 0 ]; then
    printf 'Press Enter to close this pane... ' >&2
    read -r _ || true
  fi
fi
exit "$status"
