#!/usr/bin/env bash
# Pane entrypoint: assemble the layered lazygit configuration, then exec lazygit.
#
# Config layering (verified against lazygit's docs/Config.md: LG_CONFIG_FILE
# accepts a comma-separated list of config files, later files merged over
# earlier ones):
#   1. $PLUGIN_ROOT/lazygit-config.yml           — the plugin's bundled config
#      (gui settings only; all keys live in the generated layer)
#   2. $HERDR_PLUGIN_CONFIG_DIR/generated.yml    — machine-generated by
#      scripts/gen-config-layer.sh from keys.conf + panel.conf (gui layout and
#      plugin customCommands:
#      AI commit / expand / settings); regenerated before every launch
#   3. $HERDR_PLUGIN_CONFIG_DIR/lazygit-user.yml — the user's override layer,
#      created empty (comments only) on first run; survives plugin updates
#      and always wins.
#
# NOTE: a missing file in LG_CONFIG_FILE is a hard startup error, so the
# generated layer is only appended when it actually exists.
#
# HERDR_LAZYGIT_ROOT is exported so the bundled config's customCommands can
# locate the plugin's scripts (e.g. scripts/ai-commit-msg.sh) by absolute path.
#
# bash 3.2 compatible (macOS default).
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
PLUGIN_ROOT="$(cd "$script_dir/.." && pwd)"
export HERDR_LAZYGIT_ROOT="$PLUGIN_ROOT"

# herdr injects HERDR_PLUGIN_CONFIG_DIR for plugin panes; fall back to a
# sensible per-user dir so the script also works when run outside herdr.
config_dir="${HERDR_PLUGIN_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/herdr-lazygit}"
mkdir -p "$config_dir"

# 每次重新打开都从窄侧栏开始,不继承上一次 pane 留下的 expanded 状态。
# 保留 panel.conf 里的其他宽度设置,只原子覆写 LAYOUT_MODE。
panel_conf="$config_dir/panel.conf"
panel_tmp="$(mktemp "${TMPDIR:-/tmp}/herdr-lazygit.panel.XXXXXX")"
if [ -f "$panel_conf" ]; then
  grep -v '^LAYOUT_MODE=' "$panel_conf" > "$panel_tmp" || true
else
  printf '%s\n' '# panel.conf — herdr-lazygit 面板几何与布局状态。' > "$panel_tmp"
fi
printf "%s\n" "LAYOUT_MODE='sidebar'" >> "$panel_tmp"
mv "$panel_tmp" "$panel_conf"

user_config="$config_dir/lazygit-user.yml"
if [ ! -f "$user_config" ]; then
  cat > "$user_config" <<'EOF'
# lazygit-user.yml — your personal override layer for the herdr-lazygit plugin.
#
# Settings here are merged OVER the plugin's bundled lazygit-config.yml
# (lazygit merges the comma-separated LG_CONFIG_FILE list left to right).
# Add any lazygit config keys you want to customize, e.g.:
#
#   gui:
#     nerdFontsVersion: "3"
#
# Full reference: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
EOF
fi

# 生成中间层(幂等,输入没变时是纯 stat 级开销);失败也不拦启动——
# generated.yml 缺失时降级为「出厂 + 用户」两层,插件键位暂不可用而已。
bash "$script_dir/gen-config-layer.sh" || true

generated="$config_dir/generated.yml"
layers="$PLUGIN_ROOT/lazygit-config.yml"
if [ -f "$generated" ]; then
  layers="$layers,$generated"
fi
layers="$layers,$user_config"

export LG_CONFIG_FILE="$layers"
exec lazygit
